// 数据来源：docs/available-model-capabilities-2026-09-07.md。
// 按厂商和完整模型 ID 匹配，避免同名模型的接入限制互相覆盖。
export type ModelCapability = {
  context: string
  isLlm: boolean
  isInputMultimodal: boolean
  isEmbedding: boolean
  canGenerateImage: boolean
}

const capabilities: Record<string, ModelCapability> = {
  "openrouter|minimax/minimax-m3:free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "openrouter|nvidia/nemotron-3-nano-30b-a3b": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "openrouter|inclusionai/ling-3.0-flash-sante:free": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "openrouter|openrouter/free": {"context":"200K","isLlm":false,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "openrouter|minimax/minimax-m2.5": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "openrouter|~z-ai/glm-latest": {"context":"1.31M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "bynara|minimax-m3-free": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "bynara|longcat-2.0-free": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "bynara|muse-spark-1.2-contributor-free": {"context":"未知","isLlm":false,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "sensenova|glm-5.2": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "sensenova|deepseek-v4-pro": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "sensenova|sensenova-6.8-flash-lite": {"context":"未知","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "sensenova|deepseek-v4-flash": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|qwen3.8-27b": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|deepseek-v4-flash-vision-exp": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|glm-5.3-flash": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|hy3": {"context":"256K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|deepseek-v4-flash": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|minimax-m2.7": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|hy4-preview": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "b.ai|qwen3.8-flash": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "rntm|ling-3.0-flash-sante": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|free": {"context":"200K","isLlm":false,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "rntm|north-mini-code": {"context":"256K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|dots-3-note-preview": {"context":"512K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "rntm|minimax-m3": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "rntm|lfm-2.5-2.6b": {"context":"128K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|nemotron-3.5-content-safety": {"context":"128K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "rntm|nemotron-3-super-120b-a12b": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|minimax-m2.7": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|nemotron-3.5-lightning": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "rntm|nemotron-3-ultra-550b-a55b": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gpt-4o-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gpt-4.1-mini-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gpt-5.5-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gpt-4.1-nano-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gemini-3.5-flash-lite-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gemini-3-flash-preview-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gpt-4.1-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-5.3-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-5.1-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gemini-3.6-flash-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-minimax-m3-free": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gemini-3.8-flash-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|gemini-3.7-flash-free": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-minimax-m2-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|glm-4.7-flash-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-minimax-m2.1-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-minimax-m2.5-free": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-5.2-free": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-4.6-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-4.7-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "aihubmix|coding-glm-5-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "opencode zen|ling-3.0-flash-fin-free": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "opencode zen|laguna-s-2.1-free": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "gmi cloud|minimaxai/minimax-m3": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "gmi cloud|minimaxai/minimax-m2.7": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "zenmux|z-ai/glm-4.6v-flash-free": {"context":"200K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "zenmux|dots-studio/dots3-note-prev": {"context":"393K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "zenmux|z-ai/glm-4.7-flash-free": {"context":"200K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/nemotron-3.5-content-safety": {"context":"128K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|minimaxai/minimax-m3": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/riva-translate-4b-instruct-v2": {"context":"8K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|meta/muse-glimmer-30b": {"context":"131K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/nemotron-3-ultra-550b-a55b": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|google/diffusiongemma-26b-a4b-it": {"context":"262K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/ising-calibration-1.5-31b": {"context":"262K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|moonshotai/kimi-k3": {"context":"1.05M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/nemotron-3.5-lightning-30b-a3b": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {"context":"256K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|poolside/laguna-xs-2.1": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|deepseek-ai/deepseek-v4-flash-0731": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "nvidia nim|deepseek-ai/deepseek-v4-pro-0813": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "gorouter|claude-opus-5": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "gorouter|claude-opus-5-thinking": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "gorouter|claude-opus-4-8-thinking": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "gorouter|claude-opus-4-8": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|qwen/qwen3.8-27b": {"context":"131K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|allam-2-7b": {"context":"4K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|openai/gpt-oss-20b": {"context":"128K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|openai/gpt-oss-safeguard-20b": {"context":"未知","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|openai/gpt-oss-120b": {"context":"128K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|qwen/qwen3.6-27b": {"context":"131K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|groq/compound-mini": {"context":"131K","isLlm":false,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "groq cloud|groq/compound": {"context":"131K","isLlm":false,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|minicpm5-1b": {"context":"131K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|deepseek-v4-flash-vision-exp": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|glm-5.3-flash": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|deepseek-v4-flash": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|minicpm-v46": {"context":"256K/262K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "amd radeon cloud|qwen3.8-flash-next": {"context":"262K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "flatkey|deepseek-v4-flash": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "flatkey|deepseek-v4-flash-fk-hs": {"context":"未知","isLlm":false,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|minimax-m3-free": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|deepseek-v4-flash-0731": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|deepseek-v4-flash-vision-exp": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|ling-3.0-flash-fin-free": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|deepseek-v4-flash": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|nemotron-3-ultra-550b-a55b-free": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|north-mini-code-free": {"context":"256K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|deepseek-v4-flash-latest": {"context":"1M","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|laguna-s-2.1-free": {"context":"262K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|minimax-m2.7-free": {"context":"205K","isLlm":true,"isInputMultimodal":false,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|nemotron-3.5-content-safety-free": {"context":"128K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|nemotron-3-nano-omni-30b-a3b-reasoning-free": {"context":"256K","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
  "experiential labs|qwen3.8-27b": {"context":"1M","isLlm":true,"isInputMultimodal":true,"isEmbedding":false,"canGenerateImage":false},
}

export function getModelCapability(model: { id: string; providerName: string }): ModelCapability {
  return capabilities[`${model.providerName}|${model.id}`.toLowerCase()] ?? {
    context: '未知',
    isLlm: false,
    isInputMultimodal: false,
    isEmbedding: false,
    canGenerateImage: false,
  }
}

