import type { RadarEnv } from './domain/env'
import type { RefreshQueueMessage } from './domain/refresh'
import type { SvgEvaluationQueueMessage } from './domain/svg-evaluation'
import { startRefresh, processRefreshMessage } from './services/refresh-service'
import { processSvgEvaluationMessage, scheduleSvgEvaluations } from './services/svg-evaluation-service'
// @ts-expect-error - generated by opennextjs-cloudflare build
import generatedWorker from '../.open-next/worker.js'

export default {
  ...generatedWorker,
  async scheduled(event: ScheduledEvent, env: RadarEnv, ctx: ExecutionContext): Promise<void> {
    console.error(`[scheduled] cron fired: ${event.cron}`)
    if (event.cron === '7 * * * *') {
      const queue = env.SVG_EVALUATION_QUEUE
      if (!queue) throw new Error('Missing SVG_EVALUATION_QUEUE binding')
      const svgPromise = scheduleSvgEvaluations(env, queue).then((count) => {
        console.error(`[scheduled] SVG evaluations enqueued: ${count}`)
      })
      ctx.waitUntil(svgPromise)
      await svgPromise
      return
    }
    if (!env.REFRESH_QUEUE) throw new Error('Missing REFRESH_QUEUE binding')
    const refreshPromise = startRefresh(env, env.REFRESH_QUEUE as Queue<RefreshQueueMessage>)
      .then((result) => {
        console.error(`[scheduled] refresh enqueue result: ${JSON.stringify(result)}`)
      })
      .catch((error) => {
        console.error('[scheduled] refresh enqueue failed', error)
        throw error
      })

    ctx.waitUntil(refreshPromise)
    await refreshPromise
  },
  async queue(batch: MessageBatch<RefreshQueueMessage | SvgEvaluationQueueMessage>, env: RadarEnv, _ctx: ExecutionContext): Promise<void> {
    console.error(`[queue] received batch: ${batch.messages.length}`)
    const isSvgEvaluationBatch = batch.messages.every((message) => 'evaluationId' in message.body)
    if (isSvgEvaluationBatch) {
      for (const message of batch.messages) {
        const body = message.body as SvgEvaluationQueueMessage
        try {
          await processSvgEvaluationMessage(env, body)
          message.ack()
        } catch (error) {
          console.error(`[svg-evaluation:${body.evaluationId}] consumer failed, will retry`, error)
          message.retry({ delaySeconds: 60 })
        }
      }
      return
    }
    if (!env.REFRESH_QUEUE) throw new Error('Missing REFRESH_QUEUE binding')
    const queue = env.REFRESH_QUEUE as Queue<RefreshQueueMessage>
    for (const message of batch.messages) {
      const body = message.body as RefreshQueueMessage
      const { refreshId } = body
      try {
        await processRefreshMessage(env, queue, body)
        message.ack()
      } catch (error) {
        console.error(`[queue:${refreshId}] consumer failed, will retry`, error)
        message.retry({ delaySeconds: 10 })
      }
    }
  },
}
