import type { RadarEnv } from './domain/env'
import type { RefreshQueueMessage } from './domain/refresh'
import { startRefresh, processRefreshMessage } from './services/refresh-service'
// @ts-expect-error - generated by opennextjs-cloudflare build
import generatedWorker from '../.open-next/worker.js'

export default {
  ...generatedWorker,
  async scheduled(event: ScheduledEvent, env: RadarEnv, ctx: ExecutionContext): Promise<void> {
    console.error(`[scheduled] cron fired: ${event.cron}`)
    const refreshPromise = startRefresh(env, env.REFRESH_QUEUE as Queue<RefreshQueueMessage>)
      .then((result) => {
        console.error(`[scheduled] refresh enqueue result: ${JSON.stringify(result)}`)
      })
      .catch((error) => {
        console.error('[scheduled] refresh enqueue failed', error)
        throw error
      })

    ctx.waitUntil(refreshPromise)
    await refreshPromise
  },
  async queue(batch: MessageBatch<RefreshQueueMessage>, env: RadarEnv, _ctx: ExecutionContext): Promise<void> {
    console.error(`[queue] received batch: ${batch.messages.length}`)
    const queue = env.REFRESH_QUEUE as Queue<RefreshQueueMessage>
    for (const message of batch.messages) {
      const { refreshId } = message.body
      try {
        await processRefreshMessage(env, queue, message.body)
        message.ack()
      } catch (error) {
        console.error(`[queue:${refreshId}] consumer failed, will retry`, error)
        message.retry({ delaySeconds: 10 })
      }
    }
  },
}
